In [2]:
import numpy as np

In [3]:
coords = np.array([[[0.1,0.1,0.1],[0.2,0.1,0.1],[0.3,0.1,0.1],[0.4,0.1,0.1]],
                   [[0.2,0.1,0.1],[0.3,0.1,0.1],[0.4,0.1,0.1],[0.5,0.1,0.1]],
                   [[0.3,0.1,0.1],[0.4,0.1,0.1],[0.5,0.1,0.1],[0.6,0.1,0.1]],
                   [[0.4,0.1,0.1],[0.5,0.1,0.1],[0.6,0.1,0.1],[0.7,0.1,0.1]],
                   [[0.5,0.1,0.1],[0.6,0.1,0.1],[0.7,0.1,0.1],[0.8,0.1,0.1]],
                   [[0.6,0.1,0.1],[0.7,0.1,0.1],[0.8,0.1,0.1],[0.9,0.1,0.1]],
                   [[0.7,0.1,0.1],[0.8,0.1,0.1],[0.9,0.1,0.1],[0.0,0.1,0.1]]])

latt = np.array([[10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10]])

In [4]:
print(coords.shape)
swap = np.swapaxes(coords, 0, 1)
print(swap.shape)


(7, 4, 3)
(4, 7, 3)


In [5]:
print(latt.shape)
print(coords.shape)

cart = swap * latt
print(cart)

(7, 3)
(7, 4, 3)
[[[1. 1. 1.]
  [2. 1. 1.]
  [3. 1. 1.]
  [4. 1. 1.]
  [5. 1. 1.]
  [6. 1. 1.]
  [7. 1. 1.]]

 [[2. 1. 1.]
  [3. 1. 1.]
  [4. 1. 1.]
  [5. 1. 1.]
  [6. 1. 1.]
  [7. 1. 1.]
  [8. 1. 1.]]

 [[3. 1. 1.]
  [4. 1. 1.]
  [5. 1. 1.]
  [6. 1. 1.]
  [7. 1. 1.]
  [8. 1. 1.]
  [9. 1. 1.]]

 [[4. 1. 1.]
  [5. 1. 1.]
  [6. 1. 1.]
  [7. 1. 1.]
  [8. 1. 1.]
  [9. 1. 1.]
  [0. 1. 1.]]]


In [6]:
swap_back = np.swapaxes(cart, 0, 1)
print(swap_back)

[[[1. 1. 1.]
  [2. 1. 1.]
  [3. 1. 1.]
  [4. 1. 1.]]

 [[2. 1. 1.]
  [3. 1. 1.]
  [4. 1. 1.]
  [5. 1. 1.]]

 [[3. 1. 1.]
  [4. 1. 1.]
  [5. 1. 1.]
  [6. 1. 1.]]

 [[4. 1. 1.]
  [5. 1. 1.]
  [6. 1. 1.]
  [7. 1. 1.]]

 [[5. 1. 1.]
  [6. 1. 1.]
  [7. 1. 1.]
  [8. 1. 1.]]

 [[6. 1. 1.]
  [7. 1. 1.]
  [8. 1. 1.]
  [9. 1. 1.]]

 [[7. 1. 1.]
  [8. 1. 1.]
  [9. 1. 1.]
  [0. 1. 1.]]]


In [7]:
def TOR(cart, latt):

   wrapped = cart
   pos_diff = np.diff(wrapped, axis=1)
   wrapped_part = pos_diff - np.floor(pos_diff/latt[1:] + 1/2) * latt[1:]
   wrapped_part = np.swapaxes(wrapped_part, 0,1)

   unwrapped = [cart[:,0,:]]
   for i, w in enumerate(wrapped_part):
      unwrapped.append(unwrapped[i] + w)

   unwrapped = np.array(unwrapped)
   
   return unwrapped, wrapped_part

diff, no_diff = TOR(cart, latt)
print(diff)

[[[ 1.  1.  1.]
  [ 2.  1.  1.]
  [ 3.  1.  1.]
  [ 4.  1.  1.]]

 [[ 2.  1.  1.]
  [ 3.  1.  1.]
  [ 4.  1.  1.]
  [ 5.  1.  1.]]

 [[ 3.  1.  1.]
  [ 4.  1.  1.]
  [ 5.  1.  1.]
  [ 6.  1.  1.]]

 [[ 4.  1.  1.]
  [ 5.  1.  1.]
  [ 6.  1.  1.]
  [ 7.  1.  1.]]

 [[ 5.  1.  1.]
  [ 6.  1.  1.]
  [ 7.  1.  1.]
  [ 8.  1.  1.]]

 [[ 6.  1.  1.]
  [ 7.  1.  1.]
  [ 8.  1.  1.]
  [ 9.  1.  1.]]

 [[ 7.  1.  1.]
  [ 8.  1.  1.]
  [ 9.  1.  1.]
  [10.  1.  1.]]]


In [8]:
print(np.diff(diff, axis=0).shape)
print(no_diff.shape)
np.testing.assert_equal(np.diff(diff,axis=0), no_diff)


(6, 4, 3)
(6, 4, 3)


In [9]:
latt = np.array([[[10,0,0],[0,10,0],[0,0,10]],
                 [[10,0,0],[0,10,0],[0,0,10]],
                 [[10,0,0],[0,10,0],[0,0,10]],
                 [[10,0,0],[0,10,0],[0,0,10]],
                 [[10,0,0],[0,10,0],[0,0,10]],
                 [[10,0,0],[0,10,0],[0,0,10]],
                 [[10,0,0],[0,10,0],[0,0,10]]])

print(np.all(latt == latt[0]))

test_zeros = np.zeros(latt.shape)
test_latt = latt
test_latt = np.subtract(test_latt, test_latt, where=np.tile(np.eye(3), (test_latt.shape[0],1,1)) != 0)
print(np.isclose(test_latt, test_zeros).all())

True
False


In [10]:
coords = np.array([[[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.5,0.5,0.5],[0.9,0.9,0.9]]]
                   )
print(coords.shape)
coords = np.expand_dims(coords, axis=2)
print(coords.shape)

latt   = np.array([[[2,0,0],[0,2,0],[0,0,2]],
                   [[2,0,0],[0,2,0],[0,0,2]],
                   [[2,0,0],[0,2,0],[0,0,2]],
                   [[2,0,0],[0,2,0],[0,0,2]],
                   [[2,0,0],[0,2,0],[0,0,2]],
                   [[2,0,0],[0,2,0],[0,0,2]],
                   [[2,0,0],[0,2,0],[0,0,2]]]
                  )

coords = np.concatenate(coords, axis=1)
print(coords.shape)
wrapped = np.einsum('ijk,jkl->jik', coords, latt)
print(wrapped)

(7, 4, 3)
(7, 4, 1, 3)
(4, 7, 3)
[[[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]

 [[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]

 [[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]

 [[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]

 [[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]

 [[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]

 [[0.2 0.2 0.2]
  [0.4 0.4 0.4]
  [1.  1.  1. ]
  [1.8 1.8 1.8]]]


In [11]:
print(coords[0])
print(latt[0])
print(np.einsum('ijk,jkl->ijk', coords, latt)[0])

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
[[2 0 0]
 [0 2 0]
 [0 0 2]]
[[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]


In [17]:
mat = np.array([[[10,0,0],[0,10,0],[0,0,10]],
                [[10,0,0],[0,10,0],[0,0,10]],
                [[10,0,0],[0,10,0],[0,0,10]]
                ])
mat_inv = np.linalg.inv(mat)

print(mat)
print(mat_inv)

[[[10  0  0]
  [ 0 10  0]
  [ 0  0 10]]

 [[10  0  0]
  [ 0 10  0]
  [ 0  0 10]]

 [[10  0  0]
  [ 0 10  0]
  [ 0  0 10]]]
[[[0.1 0.  0. ]
  [0.  0.1 0. ]
  [0.  0.  0.1]]

 [[0.1 0.  0. ]
  [0.  0.1 0. ]
  [0.  0.  0.1]]

 [[0.1 0.  0. ]
  [0.  0.1 0. ]
  [0.  0.  0.1]]]
