In [19]:
import numpy as np

In [20]:
coords = np.array([[[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]],
                   [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.4,0.4,0.4]]])

latt = np.array([[10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10],
                 [10,10,10]])

In [21]:
print(coords.shape)
swap = np.swapaxes(coords, 0, 1)
print(swap.shape)


(7, 4, 3)
(4, 7, 3)


In [22]:
print(latt.shape)
print(coords.shape)

cart = swap * latt
print(cart)

(7, 3)
(7, 4, 3)
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]


In [23]:
swap_back = np.swapaxes(cart, 0, 1)
print(swap_back)

[[[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]]


In [66]:
wrapped = cart
pos_diff = np.diff(wrapped, axis=1)
wrapped_part = pos_diff + np.floor(pos_diff/latt[1:] + 1/2) * latt[1:]
wrapped_part = np.swapaxes(wrapped_part, 0,1)
#print(wrapped_part)

unwrapped = [cart[:,0,:]]
for i, w in enumerate(wrapped_part):
   unwrapped.append(unwrapped[i] + w)

unwrapped = np.array(unwrapped)
print(unwrapped)

[[[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]

 [[1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]]]
